// src/signaling/signaling.events.js
export const SIGNALING_EVENTS = {
  JOIN_MEETING: "JOIN_MEETING",
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",
  OFFER: "OFFER",
  ANSWER: "ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE",
  JOIN_CHAT: "JOIN_CHAT",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHAT_HISTORY: "CHAT_HISTORY",
  LEAVE_CHAT: "LEAVE_CHAT",
  LEAVE_MEETING: "LEAVE_MEETING",
  ROOM_PARTICIPANTS: "room:participants",
  PARTICIPANT_MEDIA_STATE: "participant:media-state",
  MEDIA_STATE: "media:state"
};
